env: dev
app:
    port: 3001
db:
    host: localhost
    port: 32768
    name: testdb
    username: tester
    password: guest1234
logger:
    directory: log
    file: access.log
    level: error
    rollingStrategy: 1d
    isPretty: true